
all_coins = [
  'ETHUSDT', 
   'DOTUSDT', 
   'BNBUSDT', 
    'ADAUSDT', 
   'BTCUSDT', 
    'XRPUSDT', 
    'LINKUSDT', 
    'MATICUSDT', 
    'UNIUSDT',
    'ATOMUSDT', 
    'FILUSDT', 
    'VETUSDT', 
    'ALGOUSDT', 
    'FTMUSDT', 
    'MANAUSDT', 
   'KAVAUSDT', 
    'GALAUSDT', 
    'DYDXUSDT',
    'DOGEUSDT',
    'SOLUSDT',
    'TRXUSDT',
    'LTCUSDT',
    'XLMUSDT',
    'AVAXUSDT',
    'XMRUSDT',
    'HBARUSDT',
    'QNTUSDT',
    'APTUSDT',
    'ARBUSDT',
    'AAVEUSDT',
    'GRTUSDT',
    'SNXUSDT',
    'STXUSDT',
    'EOSUSDT',
    'EGLDUSDT',
    'SANDUSDT',
    'THETAUSDT',
    'INJUSDT',
    'RNDRUSDT',
    'AXSUSDT',
    'NEOUSDT',
    'RUNEUSDT',
    'FLOWUSDT',
    'APEUSDT',
    'CHZUSDT',
    'KLAYUSDT',
    'FXSUSDT',
    'MINAUSDT',
    'CRVUSDT',
    'SUIUSDT',
    'DASHUSDT',
    'CFXUSDT',
    'IOTAUSDT',
    'SUSHIUSDT',
    'ORDIUSDT',
    'OPUSDT',
    'TIAUSDT',
    'KASUSDT',
    'SHIBUSDT',
    'BATUSDT',
    'ARUSDT',
    'BLURUSDT',
    'ILVUSDT',
    'GMXUSDT',
    '1INCHUSDT',
    'TWTUSDT',
    'ARPAUSDT',
    'SKLUSDT',
    'ZILUSDT',
    'HOTUSDT',
    'GASUSDT',
    'AGIXUSDT',
    'COMPUSDT',
    'GLMRUSDT',
    'QTUMUSDT',
    'LRCUSDT',
    'TRBUSDT',
    'MASKUSDT',
    'ENJUSDT',
    "SSVUSDT",
    "JTOUSDT",
    "STORJUSDT",
    "ICPUSDT",
    "MEMEUSDT",
    "ENSUSDT",
    "BNTUSDT",
    "BCHUSDT",
    "ORBSUSDT",
    "WOOUSDT",
    "BSVUSDT",
    "AGLDUSDT",
    "GMTUSDT",
    "ETCUSDT",
    "WAXPUSDT",
    "RVNUSDT",
    "GALUSDT",
    "LDOUSDT",
    "WAVESUSDT",
    "ZRXUSDT",
    "MKRUSDT",
    "WLDUSDT",
    "IDUSDT",
    "FLMUSDT",
    "PEOPLEUSDT",
    "PYTHUSDT",
    "MAGICUSDT",
    "ACEUSDT",
    "KNCUSDT",
    "KSMUSDT",
    "BIGTIMEUSDT",
    "FETUSDT",
    "NEARUSDT"
    ]

best_set = [
  'ETHUSDT', 
   'DOTUSDT', 
    'ADAUSDT', 
    'XRPUSDT', 
    'LINKUSDT', 
    'MATICUSDT', 
    'UNIUSDT',
    'ATOMUSDT', 
    'FILUSDT', 
    'VETUSDT', 
    'ALGOUSDT', 
    'FTMUSDT', 
   'KAVAUSDT', 
    'GALAUSDT', 
    'DOGEUSDT',
    'SOLUSDT',
    'AVAXUSDT',
    'HBARUSDT',
    'QNTUSDT',
    'APTUSDT',
    'ARBUSDT',
    'GRTUSDT',
    'SNXUSDT',
    'STXUSDT',
    'EOSUSDT',
    'SANDUSDT',
    'INJUSDT',
    'RNDRUSDT',
    'NEOUSDT',
    'FLOWUSDT',
    'APEUSDT',
    'KLAYUSDT',
    'FXSUSDT',
    'MINAUSDT',
    'CRVUSDT',
    'SUIUSDT',
    'DASHUSDT',
    'CFXUSDT',
    'IOTAUSDT',
    'SUSHIUSDT',
    'OPUSDT',
    'BATUSDT',
    '1INCHUSDT',
    'TWTUSDT',
    'ARPAUSDT',
    'SKLUSDT',
    'ZILUSDT',
    'HOTUSDT',
    'AGIXUSDT',
    'COMPUSDT',
    'GLMRUSDT',
    'QTUMUSDT',
    'TRBUSDT',
    'MASKUSDT',
    "SSVUSDT",
    "STORJUSDT",
    "ICPUSDT",
    "MEMEUSDT",
    "ENSUSDT",
    "WOOUSDT",
    "BSVUSDT",
    "GMTUSDT",
    "RVNUSDT",
    "GALUSDT",
    "LDOUSDT",
    "WAVESUSDT",
    "MKRUSDT",
    "PYTHUSDT",
    "MAGICUSDT",
    "KSMUSDT",
    "FETUSDT",
    ]

best_set_dict = {
    'ATOMUSDT': 35,
    'DASHUSDT': 35,
    'ADAUSDT': 30,
    'IOTAUSDT': 30,
    'ALGOUSDT': 27,
    'SKLUSDT': 26,
    'FILUSDT': 25,
    'MANAUSDT': 25,
    'GRTUSDT': 25,
    'SUSHIUSDT': 25,
    'QTUMUSDT': 24,
    'AVAXUSDT': 22,
    'VETUSDT': 20,
    'DOGEUSDT': 20,
    'EGLDUSDT': 20,
    'RUNEUSDT': 18,
    '1INCHUSDT': 18,
    'HOTUSDT': 18,
    'AAVEUSDT': 17,
    'FTMUSDT': 16,
    'KAVAUSDT': 16,
    'LINKUSDT': 15,
    'SOLUSDT': 10,
    'GALAUSDT': 10,
    'SANDUSDT': 10,
    'NEOUSDT': 11,
    'MINAUSDT': 9,
    'HBARUSDT': 8,
    'GMXUSDT': 5,
    'FLOWUSDT': 5,
    'KLAYUSDT': 5,
    'LTCUSDT': 5,
    'XLMUSDT': 5,
    'AGIXUSDT': 5,
    'ARBUSDT': 4,
    'APTUSDT': 4,
    'OPUSDT': 4,
    'CFXUSDT': 2,
    'SUIUSDT': 2,
    'QNTUSDT': 2,
    'GLMRUSDT': 1,
    'TRXUSDT': 14,
    'CRVUSDT': 18,
    'ZILUSDT': 25,
    'TRBUSDT': 17,

    "ICPUSDT": 21,
    "MEMEUSDT": 4,
    "ENSUSDT": 4,
    "BCHUSDT": 12,
    "WOOUSDT": 5,
    "GMTUSDT": 6,
    "ETCUSDT": 12,
    "WAXPUSDT": 3,
    "RVNUSDT": 20,
    "GALUSDT": 6,
    "LDOUSDT": 4,
    "WAVESUSDT": 20,
    "FLMUSDT": 30,
    "KNCUSDT": 21,
}

search_set = [
    'XRPUSDT',
    'DOGEUSDT',
    'KAVAUSDT',
    'IOTAUSDT',
    'ALGOUSDT',
    'SANDUSDT',
    'EOSUSDT',
    'ATOMUSDT',
]