all_coins = [
    'ETHUSDT', 
   'DOTUSDT', 
   'BNBUSDT', 
    'ADAUSDT', 
   'BTCUSDT', 
    'XRPUSDT', 
    'LINKUSDT', 
    'MATICUSDT', 
    'UNIUSDT',
    'ATOMUSDT', 
    'FILUSDT', 
    'VETUSDT', 
    'ALGOUSDT', 
    'FTMUSDT', 
    'MANAUSDT', 
   'KAVAUSDT', 
    'GALAUSDT', 
    'DYDXUSDT',
    'DOGEUSDT',
    'SOLUSDT',
    'TRXUSDT',
    'LTCUSDT',
    'XLMUSDT',
    'AVAXUSDT',
    'XMRUSDT',
    'HBARUSDT',
    'QNTUSDT',
    'APTUSDT',
    'ARBUSDT',
    'AAVEUSDT',
    'GRTUSDT',
    'SNXUSDT',
    'STXUSDT',
    'EOSUSDT',
    'EGLDUSDT',
    'SANDUSDT',
    'THETAUSDT',
    'INJUSDT',
    'RNDRUSDT',
    'AXSUSDT',
    'NEOUSDT',
    'RUNEUSDT',
    'FLOWUSDT',
    'APEUSDT',
    'CHZUSDT',
    'KLAYUSDT',
    'FXSUSDT',
    'MINAUSDT',
    'CRVUSDT',
    'SUIUSDT',
    'DASHUSDT',
    'CFXUSDT',
    'IOTAUSDT',
    'SUSHIUSDT',
    'ORDIUSDT',
    'OPUSDT',
    'TIAUSDT',
    'KASUSDT',
    'SHIBUSDT',
    'BATUSDT',
    'ARUSDT',
    'BLURUSDT',
    'ILVUSDT',
    'GMXUSDT',
    '1INCHUSDT',
    'TWTUSDT',
    'ARPAUSDT',
    'SKLUSDT',
    'ZILUSDT',
    'HOTUSDT',
    'GASUSDT',
    'AGIXUSDT',
    'COMPUSDT',
    'GLMRUSDT',
    'QTUMUSDT',
    'LRCUSDT',
    'TRBUSDT',
    'MASKUSDT',
    'ENJUSDT',
    "SSVUSDT",
    "JTOUSDT",
    "STORJUSDT",
    "ICPUSDT",
    "MEMEUSDT",
    "ENSUSDT",
    "BNTUSDT",
    "BCHUSDT",
    "ORBSUSDT",
    "WOOUSDT",
    "BSVUSDT",
    "AGLDUSDT",
    "GMTUSDT",
    "ETCUSDT",
    "WAXPUSDT",
    "RVNUSDT",
    "GALUSDT",
    "LDOUSDT",
    "WAVESUSDT",
    "ZRXUSDT",
    "MKRUSDT",
    "WLDUSDT",
    "IDUSDT",
    "FLMUSDT",
    "PEOPLEUSDT",
    "PYTHUSDT",
    "MAGICUSDT",
    "ACEUSDT",
    "KNCUSDT",
    "KSMUSDT",
    "BIGTIMEUSDT",
    "FETUSDT",
    "NEARUSDT",
    "XTZUSDT",
    "ONTUSDT",
    "IOSTUSDT",
    "OMGUSDT",
    "SXPUSDT",
    "BANDUSDT",
    "YFIUSDT",
    "BALUSDT",
    "ICXUSDT",
    "BLZUSDT",
    "RENUSDT",
    "RSRUSDT",
    "OCEANUSDT",
    "CVCUSDT",
    "BELUSDT",
    "CTKUSDT",
    "ALPHAUSDT",
    "ANKRUSDT",
    "LITUSDT",
    "UNFIUSDT",
    "REEFUSDT",
    "SFPUSDT",
    "COTIUSDT",
    "CHRUSDT",
    "ONEUSDT",
    "STMXUSDT",
    "CELRUSDT",
    "MTLUSDT",
    "OGNUSDT",
    "NKNUSDT",
    "BAKEUSDT",
    "GTCUSDT",
    "AUDIOUSDT",
    "C98USDT",
    "CELOUSDT",
    "LPTUSDT",
    "ROSEUSDT",
    "IMXUSDT",
    "API3USDT",
    "JASMYUSDT",
    "DARUSDT",
    "STGUSDT",
    "SPELLUSDT",
    "HOOKUSDT",
    "HIGHUSDT",
    "ASTRUSDT",
    "ACHUSDT",
    "PERPUSDT",
    "TRUUSDT",
    "LQTYUSDT",
    "JOEUSDT",
    "TLMUSDT",
    "AMBUSDT",
    "LEVERUSDT",
    "RDNTUSDT",
    "EDUUSDT",
    "IDEXUSDT",
    "UMAUSDT",
    "RADUSDT",
    "KEYUSDT",
    "COMBOUSDT",
    "NMRUSDT",
    "MAVUSDT",
    "MDTUSDT",
    "PENDLEUSDT",
    "ARKMUSDT",
    "YGGUSDT",
    "SEIUSDT",
    "CYBERUSDT",
    "HIFIUSDT",
    "FRONTUSDT",
    "LOOMUSDT",
    "BONDUSDT",
    "RIFUSDT",
    "POLYXUSDT",
    "SLPUSDT",
    "TOKENUSDT",
    "BADGERUSDT",
    "1000BONKUSDT",
    "USTCUSDT",
    "ETHWUSDT",
    "AUCTIONUSDT",
    "1000RATSUSDT",
    "MOVRUSDT",
    "NFPUSDT",
    "XAIUSDT",
    "WIFUSDT",
    "MANTAUSDT",
    "ONDOUSDT",
    "LSKUSDT",
    "ALTUSDT",
    "JUPUSDT",
    "ZETAUSDT",
    "DYMUSDT",
    "OMUSDT",
    "PIXELUSDT",
    "STRKUSDT",
    "MAVIAUSDT",
    "PORTALUSDT"
]


best_set = [
    'ETHUSDT', 
    'ADAUSDT', 
    'XRPUSDT', 
    'LINKUSDT', 
    'MATICUSDT', 
    'ATOMUSDT', 
    'VETUSDT', 
    'ALGOUSDT', 
    'FTMUSDT', 
    'GALAUSDT', 
    'DOGEUSDT',
    'LTCUSDT',
    'APTUSDT',
    'ARBUSDT',
    'STXUSDT',
    'EOSUSDT',
    'EGLDUSDT',
    'SANDUSDT',
    'THETAUSDT',
    'INJUSDT',
    'NEOUSDT',
    'APEUSDT',
    'FXSUSDT',
    'MINAUSDT',
    'CRVUSDT',
    'SUIUSDT',
    'DASHUSDT',
    'CFXUSDT',
    'IOTAUSDT',
    'SUSHIUSDT',
    'OPUSDT',
    'TIAUSDT',
    'KASUSDT',
    'BATUSDT',
    'BLURUSDT',
    'GMXUSDT',
    'TWTUSDT',
    'SKLUSDT',
    'ZILUSDT',
    'GASUSDT',
    'AGIXUSDT',
    'COMPUSDT',
    'GLMRUSDT',
    'QTUMUSDT',
    'LRCUSDT',
    'TRBUSDT',
    'MASKUSDT',
    "SSVUSDT",
    "JTOUSDT",
    "ICPUSDT",
    "MEMEUSDT",
    "ENSUSDT",
    "BNTUSDT",
    "ORBSUSDT",
    "BSVUSDT",
    "GMTUSDT",
    "ETCUSDT",
    "WAXPUSDT",
    "RVNUSDT",
    "GALUSDT",
    "ZRXUSDT",
    "MKRUSDT",
    "WLDUSDT",
    "IDUSDT",
    "FLMUSDT",
    "PYTHUSDT",
    "FETUSDT",
    "NEARUSDT",
    "XTZUSDT",
    "ONTUSDT",
    "IOSTUSDT",
    "OMGUSDT",
    "BANDUSDT",
    "ICXUSDT",
    "RENUSDT",
    "RSRUSDT",
    # "CVCUSDT",
    "CTKUSDT",
    "ALPHAUSDT",
    "ANKRUSDT",
    "LITUSDT",
    "UNFIUSDT",
    "REEFUSDT",
    "SFPUSDT",
    "COTIUSDT",
    "CHRUSDT",
    "ONEUSDT",
    "OGNUSDT",
    "NKNUSDT",
    "BAKEUSDT",
    "GTCUSDT",
    "AUDIOUSDT",
    "C98USDT",
    "CELOUSDT",
    "IMXUSDT",
    "API3USDT",
    "JASMYUSDT",
    "DARUSDT",
    "STGUSDT",
    "SPELLUSDT",
    "HIGHUSDT",
    "ASTRUSDT",
    "ACHUSDT",
    "TRUUSDT",
    "LQTYUSDT",
    "JOEUSDT",
    "TLMUSDT",
    "AMBUSDT",
    "LEVERUSDT",
    "IDEXUSDT",
    "UMAUSDT",
    "RADUSDT",
    "KEYUSDT",
    "COMBOUSDT",
    "NMRUSDT",
    "MAVUSDT",
    "MDTUSDT",
    "PENDLEUSDT",
    "ARKMUSDT",
    "SEIUSDT",
    "CYBERUSDT",
    "FRONTUSDT",
    "LOOMUSDT",
    "SLPUSDT",
    "TOKENUSDT",
    "BADGERUSDT",
    "USTCUSDT",
    "NFPUSDT",
    "WIFUSDT",
    "PIXELUSDT",
    "MAVIAUSDT",
]

best_set_dict = {
    'ETHUSDT': 0.7, 
    'ADAUSDT': 0.8, 
    'XRPUSDT': 1, 
    'LINKUSDT': 0.6, 
    'MATICUSDT': 0.8, 
    'ATOMUSDT': 1, 
    'VETUSDT': 1, 
    'ALGOUSDT': 0.8, 
    'FTMUSDT': 0.8, 
    'GALAUSDT': 0.8, 
    'DOGEUSDT': 1,
    'LTCUSDT': 0.8,
    'APTUSDT': 0.8,
    'ARBUSDT': 1.2,
    'STXUSDT': 0.8,
    'EOSUSDT': 0.8,
    'EGLDUSDT': 1,
    'SANDUSDT': 1,
    'THETAUSDT': 1,
    'INJUSDT': 1,
    'NEOUSDT': 1.2,
    'APEUSDT': 1.2,
    'FXSUSDT': 1.4,
    'MINAUSDT': 0.8,
    'CRVUSDT': 0.8,
    'SUIUSDT': 1.2,
    'DASHUSDT': 0.8,
    'CFXUSDT': 0.7,
    'IOTAUSDT': 1,
    'SUSHIUSDT': 0.8,
    'OPUSDT': 1.3,
    'TIAUSDT': 1,
    'KASUSDT': 1,
    'BATUSDT': 1.2,
    'BLURUSDT': 0.8,
    'GMXUSDT': 1.4,
    'TWTUSDT': 1.2,
    'SKLUSDT': 1,
    'ZILUSDT': 0.8,
    'GASUSDT': 1,
    'AGIXUSDT': 0.8,
    'COMPUSDT': 1,
    'GLMRUSDT': 0.8,
    'QTUMUSDT': 1.3,
    'LRCUSDT': 1,
    'TRBUSDT': 1,
    'MASKUSDT': 1,
    "SSVUSDT": 1,
    "JTOUSDT": 0.8,
    "ICPUSDT": 0.8,
    "MEMEUSDT": 0.8,
    "ENSUSDT": 1,
    "BNTUSDT": 1.3,
    "ORBSUSDT": 1,
    "BSVUSDT": 0.8,
    "GMTUSDT": 1,
    "ETCUSDT": 0.8,
    "WAXPUSDT": 0.8,
    "RVNUSDT": 1.2,
    "GALUSDT": 0.7,
    "ZRXUSDT": 1.2,
    "MKRUSDT": 0.8,
    "WLDUSDT": 0.8,
    "IDUSDT": 0.8,
    "FLMUSDT": 0.8,
    "PYTHUSDT": 0.8,
    "FETUSDT": 1,
    "NEARUSDT": 0.8,
    "XTZUSDT": 1,
    "ONTUSDT": 1.4,
    "IOSTUSDT": 1,
    "OMGUSDT": 0.8,
    "BANDUSDT": 1.2,
    "ICXUSDT": 1,
    "RENUSDT": 0.8,
    "RSRUSDT": 0.8,
    # "CVCUSDT": 1,
    "CTKUSDT": 1,
    "ALPHAUSDT": 1.2,
    "ANKRUSDT": 0.8,
    "LITUSDT": 1.2,
    "UNFIUSDT": 1.2,
    "REEFUSDT": 1.2,
    "SFPUSDT": 1,
    "COTIUSDT": 0.8,
    "CHRUSDT": 1,
    "ONEUSDT": 1,
    "OGNUSDT": 0.8,
    "NKNUSDT": 1,
    "BAKEUSDT": 0.8,
    "GTCUSDT": 1,
    "AUDIOUSDT": 0.8,
    "C98USDT": 0.8,
    "CELOUSDT": 1.2,
    "IMXUSDT": 1.2,
    "API3USDT": 0.8,
    "JASMYUSDT": 1.2,
    "DARUSDT": 0.8,
    "STGUSDT": 0.8,
    "SPELLUSDT": 0.8,
    "HIGHUSDT": 1,
    "ASTRUSDT": 1,
    "ACHUSDT": 1,
    "TRUUSDT": 0.8,
    "LQTYUSDT": 1,
    "JOEUSDT": 0.8,
    "TLMUSDT": 0.8,
    "AMBUSDT": 0.8,
    "LEVERUSDT": 0.8,
    "IDEXUSDT": 1,
    "UMAUSDT": 0.8,
    "RADUSDT": 1,
    "KEYUSDT": 0.8,
    "COMBOUSDT": 1,
    "NMRUSDT": 1,
    "MAVUSDT": 0.8,
    "MDTUSDT": 0.8,
    "PENDLEUSDT": 1,
    "ARKMUSDT": 1.2,
    "SEIUSDT": 0.8,
    "CYBERUSDT": 0.8,
    "FRONTUSDT": 0.8,
    "LOOMUSDT": 0.8,
    "SLPUSDT": 0.8,
    "TOKENUSDT": 0.8,
    "BADGERUSDT": 1,
    "USTCUSDT": 1.2,
    "NFPUSDT": 1,
    "WIFUSDT": 1.2,
    "PIXELUSDT": 1,
    "MAVIAUSDT": 1,
}
